### ISSUE TITLE
Scope renaming

### ISSUE THREAD

**Issue by IrwinChay** [april-tools/cirkit#181]
To do the product between circuit with different scope, we first need to have circuits with different scope

Since scope is defined when constructing RGs by numerating from 0 to `number_of_input_dimensions` (equals to the number of input layers, not the same as `num_channels`), the scope is always the same when the number of input dimension is the same

So we need to do scope renaming to actually have another circuit with different scope (perhaps after RG creation)

For example, rename scope {0, 1, 2, 3, 4} into {0, 2, 4, 8, 11}

**Comment by loreloc** [comment]
Closing this as it will be part of a much larger discussion about the implementation of the scope.
