### ISSUE TITLE
Marginalization mask

### ISSUE THREAD

**Issue by mlnpapez** [april-tools/cirkit#292]
Hi,

The current implementation of the marginal query (https://github.com/april-tools/cirkit/blob/fb4554c5e8b418611115d2c56538e5ac67cf31c4/cirkit/backend/torch/queries.py#L19C7-L19C21) integrates all samples in the minibatch for the same set of indices. Would it be possible to apply a different set of indices for each sample in the minibatch? For example, it would be nice to have an option to use a marginalization mask (with a size equal to the minibatch).

Best regards,
Milan

**Comment by loreloc** [comment]
Hi Milan, thanks for suggesting this! We plan to support the marginalization map in the [next version](https://github.com/april-tools/cirkit/milestone/3).
