### ISSUE TITLE
Upload package to pypi

### ISSUE THREAD

**Issue by loreloc** [april-tools/cirkit#296]
As per title.

**Comment by lkct** [comment]
Just to note that: based on my experience, the default github workflow for publishing suffices. (need to add pypi token to repo secrets)

We may add `--wheel` to build if we don't need sdist. (default builds both)

**Comment by loreloc** [comment]
What is the default github workflow?
Shall we use this one? https://github.com/pypa/gh-action-pypi-publish

**Comment by lkct** [comment]
> What is the default github workflow?

Click `Actions` tab on top of page -> Clock `New Workflow` button on the left -> Choose `Publish Python Package` and `Configure` -> Modify build command (L34) if needed
