### ISSUE TITLE
Allow using Gaussian input distributions in the ```image_data``` template method?

### ISSUE THREAD

**Issue by isurulucky** [april-tools/cirkit#300]
Hi, 

Cirkit already supports Gaussian input layer [1], however it's not accessible via the ```image_data``` template method.  I experimented changing the validations in [2] to support Gaussian input distributions, and it seems to work - did not test extensively though. Is there a specific reason not to support Gaussian inputs distributions for images?

Thanks, 
Isuru.

[1]. https://github.com/april-tools/cirkit/blob/main/cirkit/symbolic/layers.py#L426
[2]. https://github.com/april-tools/cirkit/blob/main/cirkit/templates/circuit_templates/data.py

**Comment by isurulucky** [comment]
Added a draft PR which reflects the changes done: https://github.com/april-tools/cirkit/pull/301

**Comment by loreloc** [comment]
Hi Isuru, thanks a lot for reporting this. We plan to merge it for the next cirkit version.

**Comment by isurulucky** [comment]
Closing as the PR is merged.
