### ISSUE TITLE
Implement/test (possibly conditional) sampling routines

### ISSUE THREAD

**Issue by loreloc** [april-tools/cirkit#55]
- Implement and test sampling routines. Ideally, it should support conditional sampling, i.e., sampling with some evidence.
- Proposed test for this method on discrete variables: (i) choose one variable $X$, (ii) choose an assignment to the rest of variables $\mathbf{Z}$, (iii) sample $X$ conditionally for $n$ times, (iv) check that the empirical frequencies are close enough to conditional probabilities $p(X\mid \mathbf{Z})$.

**Comment by mlnpapez** [comment]
Hi,

The probabilistic inference queries (https://github.com/april-tools/cirkit/blob/fb4554c5e8b418611115d2c56538e5ac67cf31c4/cirkit/backend/torch/queries.py) currently contain only unconditional sampling. Is there a plan to add conditional sampling soon?

Best regards,
Milan
